# Generated by Django 5.0.2 on 2024-02-28 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comments'),
        ),
        migrations.AlterField(
            model_name='book',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
