# Generated by Django 5.0.2 on 2024-03-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_book_comments_comments_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='file_upload',
            field=models.FileField(null=True, upload_to='upload'),
        ),
    ]
